### PR TITLE
bug(search): include title, extractedLead, extractedUrl, and extractedProviderUrl when searching

### LINKED ISSUE #334: include extractedUrl, extractedProviderUrl, and title when searching?
Per https://github.com/mozilla/chronicle/pull/329#discussion_r24628825 and #324:

> _Unrelated, but should we also be searching `extractedUrl`, `extractedProviderUrl`, and/or `title`?_

> _Basically, "title" because the `extractedTitle` will be less useful if the scraped page was behind a login (ie: facebook, or something on localhost that embedly can't touch)._

@nchapman said _"Good points. Let's do a follow up PR for these. @pdehaan will you create an issue?"_

## THIS IS THAT ISSUE!!!

### PR DESCRIPTION
**Pull request by pdehaan**
Closes #334

### CODE REVIEW

File: server/models/visits.js [hunk 1]
```diff
@@ -81,11 +81,15 @@ var visits = {
                 fuzziness: 'AUTO',
                 operator: 'and',
                 fields: [
+                  'title',
                   'extractedTitle',
                   'extractedContent',
+                  'extractedLead',
                   'extractedDescription',
+                  'extractedUrl',
```
Comment (nchapman) [inline server/models/visits.js]: The usefulness of this will really depend on tokenizer being used for this field.

File: server/models/visits.js [hunk 2]
```diff
@@ -81,11 +81,15 @@ var visits = {
...
                   'extractedProviderDisplay',
                   'extractedProviderName',
+                  'extractedProviderUrl',
```
Comment (nchapman) [inline server/models/visits.js]: This is probably a substring of `extractedUrl`. Let's drop this one.

Comment (pdehaan) [inline server/models/visits.js]: Looks like you're right: <http://localhost:9200/chronicle/_search?_source=extractedUrl,extractedProviderUrl> (or at least for my local default dataset).
