### PR TITLE
bug(search): include description when searching

### LINKED ISSUE #324: Search not finding pages by keywords in description
#### Search for msngr.js

screen shot 2015-02-11 at 9 24 11 am

#### Search for 'small messaging library' from description

screen shot 2015-02-11 at 9 25 58 am

### PR DESCRIPTION
**Pull request by 6a68**
Fixes #324 

@nchapman mind taking a look? Seems to be working for me:

screenshot 2015-02-12 14 27 32

### CODE REVIEW

File: server/models/visits.js [hunk 1]
```diff
@@ -83,6 +83,7 @@ var visits = {
                 fields: [
                   'extractedTitle',
                   'extractedContent',
+                  'extractedDescription',
```
Comment (pdehaan) [inline server/models/visits.js]: Unrelated, but should we also be searching `extractedUrl`, `extractedProviderUrl`, and/or `title`?

Basically, "title" because the `extractedTitle` will be less useful if the scraped page was behind a login (ie: facebook, or something on localhost that embedly can't touch).

Comment (nchapman) [inline server/models/visits.js]: Good points. Let's do a follow up PR for these. @pdehaan will you create an issue?

**Comment by nchapman** [comment]
:+1:

File: server/models/visits.js (hunk 1 above)
Comment (pdehaan) [inline server/models/visits.js]: Filed as #334
