### PR TITLE
fix(db): improve elasticsearch query

### LINKED ISSUE #227: improve search results
Let's tweak the elasticsearch query to search on multiple fields.
It might also be useful to keep the keywords and use those to boost matches - we could store them as a json array in postgres, i.e. an opaque json blob, and actually use them in elasticsearch.

### PR DESCRIPTION
**Pull request by 6a68**
Fixes #227 

Stole @nchapman's v0 search query, let's rock!

### CODE REVIEW

File: server/models/visits.js [hunk 1]
```diff
@@ -75,29 +75,25 @@ var visits = {
...
+          filtered: {
+            query: {
+              multiMatch: {
+                query: searchTerm,
+                fuzziness: 'AUTO',
+                operator: 'and',
+                fields: [
+                  'extractedTitle',
+                  'extractedContent',
+                  'providerDisplay',
```
Comment (nchapman) [inline server/models/visits.js]: Do these need the `extracted` prefix?

Comment (6a68) [inline server/models/visits.js]: doh, yup

**Comment by nchapman** [comment]
:+1:
